// GENERATED FILE — do not edit by hand.
// Regenerate: node --experimental-strip-types scripts/gen-iso-3166.ts
//
// Maps GSC's lowercase ISO 3166-1 alpha-3 country codes to a world-atlas
// feature key and an English display name.
//
// `key` is the atlas join key: the feature's numeric `id` where it has one,
// or its `properties.name` for the three features that have no ISO assignment
// (Kosovo, N. Cyprus, Somaliland). An EMPTY `key` means the code has no
// feature in the 110m atlas — such a country is listed with its impressions but
// is NOT drawn, because guessing a location would be worse than omitting one.
//
// 250 codes, 175 with an atlas feature.

export interface IsoCountry {
  /** world-atlas join key, or "" when the atlas has no feature for this code. */
  key: string;
  /** English display name. */
  name: string;
}

export const ISO_3166: Record<string, IsoCountry> = {
  abw: { key: "", name: "Aruba" },
  afg: { key: "004", name: "Afghanistan" },
  ago: { key: "024", name: "Angola" },
  aia: { key: "", name: "Anguilla" },
  ala: { key: "", name: "Åland Islands" },
  alb: { key: "008", name: "Albania" },
  and: { key: "", name: "Andorra" },
  are: { key: "784", name: "United Arab Emirates" },
  arg: { key: "032", name: "Argentina" },
  arm: { key: "051", name: "Armenia" },
  asm: { key: "", name: "American Samoa" },
  ata: { key: "010", name: "Antarctica" },
  atf: { key: "260", name: "French Southern Territories" },
  atg: { key: "", name: "Antigua and Barbuda" },
  aus: { key: "036", name: "Australia" },
  aut: { key: "040", name: "Austria" },
  aze: { key: "031", name: "Azerbaijan" },
  bdi: { key: "108", name: "Burundi" },
  bel: { key: "056", name: "Belgium" },
  ben: { key: "204", name: "Benin" },
  bes: { key: "", name: "Bonaire, Sint Eustatius and Saba" },
  bfa: { key: "854", name: "Burkina Faso" },
  bgd: { key: "050", name: "Bangladesh" },
  bgr: { key: "100", name: "Bulgaria" },
  bhr: { key: "", name: "Bahrain" },
  bhs: { key: "044", name: "Bahamas" },
  bih: { key: "070", name: "Bosnia and Herzegovina" },
  blm: { key: "", name: "Saint Barthélemy" },
  blr: { key: "112", name: "Belarus" },
  blz: { key: "084", name: "Belize" },
  bmu: { key: "", name: "Bermuda" },
  bol: { key: "068", name: "Bolivia" },
  bra: { key: "076", name: "Brazil" },
  brb: { key: "", name: "Barbados" },
  brn: { key: "096", name: "Brunei Darussalam" },
  btn: { key: "064", name: "Bhutan" },
  bvt: { key: "", name: "Bouvet Island" },
  bwa: { key: "072", name: "Botswana" },
  caf: { key: "140", name: "Central African Republic" },
  can: { key: "124", name: "Canada" },
  cck: { key: "", name: "Cocos (Keeling) Islands" },
  che: { key: "756", name: "Switzerland" },
  chl: { key: "152", name: "Chile" },
  chn: { key: "156", name: "People's Republic of China" },
  civ: { key: "384", name: "Cote d'Ivoire" },
  cmr: { key: "120", name: "Cameroon" },
  cod: { key: "180", name: "Democratic Republic of the Congo" },
  cog: { key: "178", name: "Republic of the Congo" },
  cok: { key: "", name: "Cook Islands" },
  col: { key: "170", name: "Colombia" },
  com: { key: "", name: "Comoros" },
  cpv: { key: "", name: "Cape Verde" },
  cri: { key: "188", name: "Costa Rica" },
  cub: { key: "192", name: "Cuba" },
  cuw: { key: "", name: "Curaçao" },
  cxr: { key: "", name: "Christmas Island" },
  cym: { key: "", name: "Cayman Islands" },
  cyp: { key: "196", name: "Cyprus" },
  cze: { key: "203", name: "Czech Republic" },
  deu: { key: "276", name: "Germany" },
  dji: { key: "262", name: "Djibouti" },
  dma: { key: "", name: "Dominica" },
  dnk: { key: "208", name: "Denmark" },
  dom: { key: "214", name: "Dominican Republic" },
  dza: { key: "012", name: "Algeria" },
  ecu: { key: "218", name: "Ecuador" },
  egy: { key: "818", name: "Egypt" },
  eri: { key: "232", name: "Eritrea" },
  esh: { key: "732", name: "Western Sahara" },
  esp: { key: "724", name: "Spain" },
  est: { key: "233", name: "Estonia" },
  eth: { key: "231", name: "Ethiopia" },
  fin: { key: "246", name: "Finland" },
  fji: { key: "242", name: "Fiji" },
  flk: { key: "238", name: "Falkland Islands (Malvinas)" },
  fra: { key: "250", name: "France" },
  fro: { key: "", name: "Faroe Islands" },
  fsm: { key: "", name: "Micronesia, Federated States of" },
  gab: { key: "266", name: "Gabon" },
  gbr: { key: "826", name: "United Kingdom" },
  geo: { key: "268", name: "Georgia" },
  ggy: { key: "", name: "Guernsey" },
  gha: { key: "288", name: "Ghana" },
  gib: { key: "", name: "Gibraltar" },
  gin: { key: "324", name: "Guinea" },
  glp: { key: "", name: "Guadeloupe" },
  gmb: { key: "270", name: "Republic of The Gambia" },
  gnb: { key: "624", name: "Guinea-Bissau" },
  gnq: { key: "226", name: "Equatorial Guinea" },
  grc: { key: "300", name: "Greece" },
  grd: { key: "", name: "Grenada" },
  grl: { key: "304", name: "Greenland" },
  gtm: { key: "320", name: "Guatemala" },
  guf: { key: "", name: "French Guiana" },
  gum: { key: "", name: "Guam" },
  guy: { key: "328", name: "Guyana" },
  hkg: { key: "", name: "Hong Kong" },
  hmd: { key: "", name: "Heard Island and McDonald Islands" },
  hnd: { key: "340", name: "Honduras" },
  hrv: { key: "191", name: "Croatia" },
  hti: { key: "332", name: "Haiti" },
  hun: { key: "348", name: "Hungary" },
  idn: { key: "360", name: "Indonesia" },
  imn: { key: "", name: "Isle of Man" },
  ind: { key: "356", name: "India" },
  iot: { key: "", name: "British Indian Ocean Territory" },
  irl: { key: "372", name: "Ireland" },
  irn: { key: "364", name: "Islamic Republic of Iran" },
  irq: { key: "368", name: "Iraq" },
  isl: { key: "352", name: "Iceland" },
  isr: { key: "376", name: "Israel" },
  ita: { key: "380", name: "Italy" },
  jam: { key: "388", name: "Jamaica" },
  jey: { key: "", name: "Jersey" },
  jor: { key: "400", name: "Jordan" },
  jpn: { key: "392", name: "Japan" },
  kaz: { key: "398", name: "Kazakhstan" },
  ken: { key: "404", name: "Kenya" },
  kgz: { key: "417", name: "Kyrgyzstan" },
  khm: { key: "116", name: "Cambodia" },
  kir: { key: "", name: "Kiribati" },
  kna: { key: "", name: "Saint Kitts and Nevis" },
  kor: { key: "410", name: "South Korea" },
  kwt: { key: "414", name: "Kuwait" },
  lao: { key: "418", name: "Lao People's Democratic Republic" },
  lbn: { key: "422", name: "Lebanon" },
  lbr: { key: "430", name: "Liberia" },
  lby: { key: "434", name: "Libya" },
  lca: { key: "", name: "Saint Lucia" },
  lie: { key: "", name: "Liechtenstein" },
  lka: { key: "144", name: "Sri Lanka" },
  lso: { key: "426", name: "Lesotho" },
  ltu: { key: "440", name: "Lithuania" },
  lux: { key: "442", name: "Luxembourg" },
  lva: { key: "428", name: "Latvia" },
  mac: { key: "", name: "Macao" },
  maf: { key: "", name: "Saint Martin (French part)" },
  mar: { key: "504", name: "Morocco" },
  mco: { key: "", name: "Monaco" },
  mda: { key: "498", name: "Moldova, Republic of" },
  mdg: { key: "450", name: "Madagascar" },
  mdv: { key: "", name: "Maldives" },
  mex: { key: "484", name: "Mexico" },
  mhl: { key: "", name: "Marshall Islands" },
  mkd: { key: "807", name: "The Republic of North Macedonia" },
  mli: { key: "466", name: "Mali" },
  mlt: { key: "", name: "Malta" },
  mmr: { key: "104", name: "Myanmar" },
  mne: { key: "499", name: "Montenegro" },
  mng: { key: "496", name: "Mongolia" },
  mnp: { key: "", name: "Northern Mariana Islands" },
  moz: { key: "508", name: "Mozambique" },
  mrt: { key: "478", name: "Mauritania" },
  msr: { key: "", name: "Montserrat" },
  mtq: { key: "", name: "Martinique" },
  mus: { key: "", name: "Mauritius" },
  mwi: { key: "454", name: "Malawi" },
  mys: { key: "458", name: "Malaysia" },
  myt: { key: "", name: "Mayotte" },
  nam: { key: "516", name: "Namibia" },
  ncl: { key: "540", name: "New Caledonia" },
  ner: { key: "562", name: "Niger" },
  nfk: { key: "", name: "Norfolk Island" },
  nga: { key: "566", name: "Nigeria" },
  nic: { key: "558", name: "Nicaragua" },
  niu: { key: "", name: "Niue" },
  nld: { key: "528", name: "Netherlands" },
  nor: { key: "578", name: "Norway" },
  npl: { key: "524", name: "Nepal" },
  nru: { key: "", name: "Nauru" },
  nzl: { key: "554", name: "New Zealand" },
  omn: { key: "512", name: "Oman" },
  pak: { key: "586", name: "Pakistan" },
  pan: { key: "591", name: "Panama" },
  pcn: { key: "", name: "Pitcairn" },
  per: { key: "604", name: "Peru" },
  phl: { key: "608", name: "Philippines" },
  plw: { key: "", name: "Palau" },
  png: { key: "598", name: "Papua New Guinea" },
  pol: { key: "616", name: "Poland" },
  pri: { key: "630", name: "Puerto Rico" },
  prk: { key: "408", name: "North Korea" },
  prt: { key: "620", name: "Portugal" },
  pry: { key: "600", name: "Paraguay" },
  pse: { key: "275", name: "State of Palestine" },
  pyf: { key: "", name: "French Polynesia" },
  qat: { key: "634", name: "Qatar" },
  reu: { key: "", name: "Reunion" },
  rou: { key: "642", name: "Romania" },
  rus: { key: "643", name: "Russian Federation" },
  rwa: { key: "646", name: "Rwanda" },
  sau: { key: "682", name: "Saudi Arabia" },
  sdn: { key: "729", name: "Sudan" },
  sen: { key: "686", name: "Senegal" },
  sgp: { key: "", name: "Singapore" },
  sgs: { key: "", name: "South Georgia and the South Sandwich Islands" },
  shn: { key: "", name: "Saint Helena" },
  sjm: { key: "", name: "Svalbard and Jan Mayen" },
  slb: { key: "090", name: "Solomon Islands" },
  sle: { key: "694", name: "Sierra Leone" },
  slv: { key: "222", name: "El Salvador" },
  smr: { key: "", name: "San Marino" },
  som: { key: "706", name: "Somalia" },
  spm: { key: "", name: "Saint Pierre and Miquelon" },
  srb: { key: "688", name: "Serbia" },
  ssd: { key: "728", name: "South Sudan" },
  stp: { key: "", name: "Sao Tome and Principe" },
  sur: { key: "740", name: "Suriname" },
  svk: { key: "703", name: "Slovakia" },
  svn: { key: "705", name: "Slovenia" },
  swe: { key: "752", name: "Sweden" },
  swz: { key: "748", name: "Eswatini" },
  sxm: { key: "", name: "Sint Maarten (Dutch part)" },
  syc: { key: "", name: "Seychelles" },
  syr: { key: "760", name: "Syrian Arab Republic" },
  tca: { key: "", name: "Turks and Caicos Islands" },
  tcd: { key: "148", name: "Chad" },
  tgo: { key: "768", name: "Togo" },
  tha: { key: "764", name: "Thailand" },
  tjk: { key: "762", name: "Tajikistan" },
  tkl: { key: "", name: "Tokelau" },
  tkm: { key: "795", name: "Turkmenistan" },
  tls: { key: "626", name: "Timor-Leste" },
  ton: { key: "", name: "Tonga" },
  tto: { key: "780", name: "Trinidad and Tobago" },
  tun: { key: "788", name: "Tunisia" },
  tur: { key: "792", name: "Türkiye" },
  tuv: { key: "", name: "Tuvalu" },
  twn: { key: "158", name: "Taiwan, Province of China" },
  tza: { key: "834", name: "United Republic of Tanzania" },
  uga: { key: "800", name: "Uganda" },
  ukr: { key: "804", name: "Ukraine" },
  umi: { key: "", name: "United States Minor Outlying Islands" },
  ury: { key: "858", name: "Uruguay" },
  usa: { key: "840", name: "United States of America" },
  uzb: { key: "860", name: "Uzbekistan" },
  vat: { key: "", name: "Holy See (Vatican City State)" },
  vct: { key: "", name: "Saint Vincent and the Grenadines" },
  ven: { key: "862", name: "Venezuela" },
  vgb: { key: "", name: "Virgin Islands, British" },
  vir: { key: "", name: "Virgin Islands, U.S." },
  vnm: { key: "704", name: "Vietnam" },
  vut: { key: "548", name: "Vanuatu" },
  wlf: { key: "", name: "Wallis and Futuna" },
  wsm: { key: "", name: "Samoa" },
  xkk: { key: "Kosovo", name: "Kosovo" },
  yem: { key: "887", name: "Yemen" },
  zaf: { key: "710", name: "South Africa" },
  zmb: { key: "894", name: "Zambia" },
  zwe: { key: "716", name: "Zimbabwe" },
};

/**
 * Resolves a GSC country code. Returns `null` for codes we have no entry for
 * at all (e.g. GSC's `zzz` unknown-region bucket), so callers can render the
 * raw code rather than silently discarding its impressions.
 */
export function lookupCountry(alpha3: string): IsoCountry | null {
  return ISO_3166[alpha3.toLowerCase()] ?? null;
}
